[rospy.client][INFO] 2021-12-09 13:09:48,930: init_node, name[/ss42/led_emitter_node], pid[7941]
[xmlrpc][INFO] 2021-12-09 13:09:48,939: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2021-12-09 13:09:48,946: ROS Slave URI: [http://ss42.local:39504/]
[xmlrpc][INFO] 2021-12-09 13:09:48,947: Started XML-RPC server [http://ss42.local:39504/]
[rospy.impl.masterslave][INFO] 2021-12-09 13:09:48,948: _ready: http://ss42.local:39504/
[xmlrpc][INFO] 2021-12-09 13:09:48,960: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-12-09 13:09:48,965: Registering with master node http://ss42.local:11311/
[rospy.init][INFO] 2021-12-09 13:09:49,047: registered with master
[rospy.rosout][INFO] 2021-12-09 13:09:49,049: initializing /rosout core topic
[rospy.rosout][INFO] 2021-12-09 13:09:49,130: connected to core topic /rosout
[rospy.simtime][INFO] 2021-12-09 13:09:49,204: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-12-09 13:09:49,355: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-12-09 13:09:49,754: topic[/ss42/led_emitter_node/switch] adding connection to [http://ss42.local:36750/], count 0
[rosout][INFO] 2021-12-09 13:09:49,777: changePattern('CAR_SIGNAL_A')
[rospy.core][INFO] 2021-12-09 13:39:38,509: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-12-09 13:39:38,616: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-12-09 13:39:38,627: topic[/ss42/led_emitter_node/switch] removing connection to http://ss42.local:36750/
[rospy.impl.masterslave][INFO] 2021-12-09 13:39:38,630: signal-2
[rospy.internal][WARNING] 2021-12-09 13:39:38,631: Unknown error initiating TCP/IP socket to ss42.local:45650 (http://ss42.local:36750/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 634, in write_header
    sock.setblocking(1)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[rospy.core][INFO] 2021-12-09 13:39:39,207: signal_shutdown [atexit]
