[rospy.client][INFO] 2021-10-22 12:36:13,528: [32minit_node, name[/ss42/forward_kinematics_node], pid[22634][0m
[xmlrpc][INFO] 2021-10-22 12:36:13,530: [32mXML-RPC server binding to 0.0.0.0:0[0m
[xmlrpc][INFO] 2021-10-22 12:36:13,531: [32mStarted XML-RPC server [http://ss42.local:38732/][0m
[rospy.init][INFO] 2021-10-22 12:36:13,532: [32mROS Slave URI: [http://ss42.local:38732/][0m
[rospy.impl.masterslave][INFO] 2021-10-22 12:36:13,532: [32m_ready: http://ss42.local:38732/[0m
[rospy.registration][INFO] 2021-10-22 12:36:13,535: [32mRegistering with master node http://ss42.local:11311/[0m
[xmlrpc][INFO] 2021-10-22 12:36:13,535: [32mxml rpc node: starting XML-RPC server[0m
[rospy.init][INFO] 2021-10-22 12:36:13,633: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-10-22 12:36:13,633: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-10-22 12:36:13,642: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-10-22 12:36:13,648: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][WARNING] 2021-10-22 12:36:13,679: [33m[/ss42/forward_kinematics_node] /home/robotikabot/duckiefleet/calibrations/kinematics/ss42.yaml does not exist. Using default.yaml.[0m
[rosout][INFO] 2021-10-22 12:36:13,733: [32m[/ss42/forward_kinematics_node] ~gain = 1.0 [0m
[rosout][INFO] 2021-10-22 12:36:13,747: [32m[/ss42/forward_kinematics_node] ~trim = 0.0 [0m
[rosout][INFO] 2021-10-22 12:36:13,764: [32m[/ss42/forward_kinematics_node] ~baseline = 0.1 [0m
[rospy.internal][INFO] 2021-10-22 12:36:13,777: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rosout][INFO] 2021-10-22 12:36:13,779: [32m[/ss42/forward_kinematics_node] ~radius = 0.0318 [0m
[rosout][INFO] 2021-10-22 12:36:13,793: [32m[/ss42/forward_kinematics_node] ~k = 27.0 [0m
[rosout][INFO] 2021-10-22 12:36:13,817: [32m[/ss42/forward_kinematics_node] Initialized.[0m
[rosout][INFO] 2021-10-22 12:36:13,819: [32m[/ss42/forward_kinematics_node] gain: 1.0 trim: 0.0 baseline: 0.1 radius: 0.0318 k: 27.0[0m
[rospy.internal][INFO] 2021-10-22 12:36:13,858: [32mtopic[/ss42/wheels_driver_node/wheels_cmd_executed] adding connection to [http://ss42.local:45040/], count 0[0m
[rospy.internal][INFO] 2021-10-22 12:36:13,897: [32mtopic[/ss42/forward_kinematics_node/velocity] adding connection to [/ss42/velocity_to_pose_node], count 0[0m
[rospy.core][INFO] 2021-10-22 12:38:28,676: [32msignal_shutdown [signal-2][0m
[rospy.internal][ERROR] 2021-10-22 12:38:28,727: [31mUnable to initiate TCP/IP socket to ss42.local:43492 (http://ss42.local:45040/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down
[0m
[rospy.internal][INFO] 2021-10-22 12:38:28,776: [32mtopic[/ss42/forward_kinematics_node/velocity] removing connection to /ss42/velocity_to_pose_node[0m
[rospy.internal][INFO] 2021-10-22 12:38:28,777: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-10-22 12:38:28,778: [32mtopic[/ss42/wheels_driver_node/wheels_cmd_executed] removing connection to http://ss42.local:45040/[0m
[rospy.impl.masterslave][INFO] 2021-10-22 12:38:28,779: [32msignal-2[0m
[rospy.core][INFO] 2021-10-22 12:38:29,294: [32msignal_shutdown [atexit][0m
