[rospy.client][INFO] 2021-10-22 11:50:45,089: [32minit_node, name[/ss42/cam_info_reader_node], pid[6167][0m
[xmlrpc][INFO] 2021-10-22 11:50:45,091: [32mXML-RPC server binding to 0.0.0.0:0[0m
[xmlrpc][INFO] 2021-10-22 11:50:45,094: [32mStarted XML-RPC server [http://ss42.local:35366/][0m
[rospy.impl.masterslave][INFO] 2021-10-22 11:50:45,094: [32m_ready: http://ss42.local:35366/[0m
[rospy.init][INFO] 2021-10-22 11:50:45,096: [32mROS Slave URI: [http://ss42.local:35366/][0m
[xmlrpc][INFO] 2021-10-22 11:50:45,098: [32mxml rpc node: starting XML-RPC server[0m
[rospy.registration][INFO] 2021-10-22 11:50:45,102: [32mRegistering with master node http://ss42.local:11311/[0m
[rospy.init][INFO] 2021-10-22 11:50:45,197: [32mregistered with master[0m
[rospy.rosout][INFO] 2021-10-22 11:50:45,197: [32minitializing /rosout core topic[0m
[rospy.rosout][INFO] 2021-10-22 11:50:45,206: [32mconnected to core topic /rosout[0m
[rospy.simtime][INFO] 2021-10-22 11:50:45,212: [32m/use_sim_time is not set, will not subscribe to simulated time [/clock] topic[0m
[rosout][INFO] 2021-10-22 11:50:45,251: [32m[/ss42/cam_info_reader_node] ~config = baseline [0m
[rosout][INFO] 2021-10-22 11:50:45,264: [32m[/ss42/cam_info_reader_node] ~cali_file_name = ss42 [0m
[rosout][INFO] 2021-10-22 11:50:45,285: [32m[/ss42/cam_info_reader_node] ~image_type = compressed [0m
[rosout][WARNING] 2021-10-22 11:50:45,294: [33m[/ss42/cam_info_reader_node] Can't find calibration file: /home/robotikabot/duckiefleet/calibrations/camera_intrinsic/ss42.yaml.
Using default calibration instead.[0m
[rosout][INFO] 2021-10-22 11:50:45,295: [32m[/ss42/cam_info_reader_node] Using calibration file: /home/robotikabot/duckiefleet/calibrations/camera_intrinsic/default.yaml[0m
[rosout][INFO] 2021-10-22 11:50:45,343: [32m[/ss42/cam_info_reader_node] CameraInfo: header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "/ss42/camera_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [-0.2565888993516047, 0.04481160508242147, -0.00505275149956019, 0.001308569367976665, 0]
K: [307.7379294605756, 0, 329.692367951685, 0, 314.9827773443905, 244.4605588877848, 0, 0, 1]
R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
P: [210.1107940673828, 0, 327.2577820024981, 0, 0, 253.8408660888672, 239.9969353923052, 0, 0, 0, 1, 0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False[0m
[rosout][WARNING] 2021-10-22 11:50:45,344: [33m[/ss42/cam_info_reader_node] ==============CompressedImage[0m
[rospy.internal][INFO] 2021-10-22 11:50:45,525: [32mtopic[/rosout] adding connection to [/rosout], count 0[0m
[rospy.internal][INFO] 2021-10-22 11:50:45,865: [32mtopic[/ss42/camera_node/image/compressed] adding connection to [http://ss42.local:44065/], count 0[0m
[rospy.core][INFO] 2021-10-22 11:52:30,958: [32msignal_shutdown [signal-2][0m
[rosout][INFO] 2021-10-22 11:52:30,959: [32m[/ss42/cam_info_reader_node] Shutdown.[0m
[rospy.internal][INFO] 2021-10-22 11:52:31,019: [32mtopic[/rosout] removing connection to /rosout[0m
[rospy.internal][INFO] 2021-10-22 11:52:31,020: [32mtopic[/ss42/camera_node/image/compressed] removing connection to http://ss42.local:44065/[0m
[rospy.impl.masterslave][INFO] 2021-10-22 11:52:31,021: [32msignal-2[0m
[rospy.internal][WARNING] 2021-10-22 11:52:31,028: [33mUnknown error initiating TCP/IP socket to ss42.local:33490 (http://ss42.local:44065/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
[0m
[rospy.core][INFO] 2021-10-22 11:52:31,587: [32msignal_shutdown [atexit][0m
